[package]
authors = ["Ivan Nejgebauer <inejge@gmail.com>", "Gregor Reitzenstein <dean4devil@paranoidlabs.org>"]
description = "Pure-Rust LDAPv3 Client"
documentation = "https://docs.rs/ldap3"
keywords = ["ldap", "client", "tokio", "async"]
license = "MIT/Apache-2.0"
name = "ldap3"
readme = "README.md"
repository = "https://github.com/inejge/ldap3"
version = "0.6.1"

[dependencies]
byteorder = "1"
bytes = "0.4"
futures = "0.1"
lazy_static = "1.1"
log = "0.4"
native-tls = { version = "0.2", optional = true }
nom = "2.0"
tokio-codec = "0.1"
tokio = {version = "0.1", features = ["tcp"]}
tokio-current-thread = "0.1"
# tokio-proto = { git = "https://github.com/red75prime/tokio-proto" }
tokio-proto = { path = "../tokio-proto" }
# tower = { git = "https://github.com/tower-rs/tower" }
# tower-service = { git = "https://github.com/tower-rs/tower" }
tokio-io = "0.1"
tokio-tcp = "0.1"
tokio-service = "0.1"
tokio-timer = "0.2"
url = "1.4.0"

[target.'cfg(all(unix, not(feature = "minimal")))'.dependencies]
tokio-uds = "0.1.4" 
tokio-uds-proto = "0.1"

[dependencies.lber]
path = "lber"
version = "0.1.6"

[dependencies.tokio-tls]
version = "0.2"
optional = true

[features]
default = ["tls"]
tls = ["native-tls", "tokio-tls"]
minimal = []

[dev-dependencies]
env_logger = "0.5"
maplit = "1.0"

[workspace]
members = [".", "lber"]
